### PR TITLE
Switch to using a UITableViewController

### PR DESCRIPTION
**Pull request by caramdache**
Use a UITableViewController and set row height according to iOS 8 guidelines.
Remove unnecessary UIButton.
Move Firebase setup in its own setup method.
Add observers for :changed and :removed

### CODE REVIEW

**Comment by colinta** [comment]
Looks cool, thanks!  I've never been particularly fond of the `UITableViewController`, myself.

**Comment by caramdache** [comment]
You’re missing a lot then… ;-)
Thanks for integrating the patch. 

2 more to follow.

**Comment by colinta** [comment]
Ha, well `UITableViewController` actually does fairly *little* outside a normal `UIViewController`.  It adds a table view, sets the delegate and datasource, and it "deselects" the tapped row during `viewDidAppear`.  That's not a ton of time saved, and you lose the ability to easily add other views to your hierarchy (`controller.view == controller.tableView`).  No thanks!  I just wire those up myself, and keep the flexibility.

**Comment by caramdache** [comment]
Scrolling under the navigationBar? searchBar that does not get screwed (when collapsing the navigationBar)? Rotation? There’s too much that can go wrong and I prefer to add my additional views to the tableHeaderView.

YMMV.

**Pull request merged**
